services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      - NEXUS_DATASTORE_NEXUS_JDBCURL=${NEXUS_DATASTORE_NEXUS_JDBCURL}
      - NEXUS_DATASTORE_NEXUS_USERNAME=${NEXUS_DATASTORE_NEXUS_USERNAME}
      - NEXUS_DATASTORE_NEXUS_PASSWORD=${NEXUS_DATASTORE_NEXUS_PASSWORD}
      - INSTALL4J_ADD_VM_PARAMS=${INSTALL4J_ADD_VM_PARAMS}
    volumes:
      - "nexus-data:/nexus-data"
      - ${LICENSE_FILE}:/nexus-data/license.lic
    ports:
      - "8081:8081"

volumes:
  nexus-data:
