services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem"
      - "-c"
      - "ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/nexus.sql:/docker-entrypoint-initdb.d/nexus.sql

  nexus:
    image: sonatype/nexus3
    container_name: nexus-ldap
    environment:
      INSTALL4J_ADD_VM_PARAMS: >
        -Xms8g
        -Xmx8g
        -Dnexus.licenseFile=/nexus-data/license.lic
        -Dnexus.datastore.enabled=true
        -Dnexus.datastore.nexus.jdbcUrl=jdbc:postgresql://postgres/nxrm?ssl=true&sslmode=require
        -Dnexus.datastore.nexus.username=nxrm
        -Dnexus.datastore.nexus.password=nxrm123
    volumes:
      - "nexus-data:/nexus-data"
      - ${LICENSE_FILE}:/nexus-data/license.lic
    ports:
      - "8081:8081"

volumes:
  pgdata:
  nexus-data:

