services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      INSTALL4J_ADD_VM_PARAMS: >
        -Xms8g
        -Xmx8g
        -Dnexus.licenseFile=/nexus-data/license.lic
        -Dnexus.datastore.enabled=true
        -Dnexus.datastore.nexus.jdbcUrl=jdbc:postgresql://postgres/nxrm?ssl=true&sslmode=require
        -Dnexus.datastore.nexus.username=nxrm
        -Dnexus.datastore.nexus.password=nxrm123
    volumes:
      - "nexus-data:/nexus-data"
      - ${LICENSE_FILE}:/nexus-data/license.lic
    ports:
      - "8081:8081"

volumes:
  nexus-data:
